services:
  diun:
    image: crazymax/diun:latest
    command: serve
    volumes:
      - /opt/docker_volumes/diun/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Berlin
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
    labels:
      - diun.enable=true
    restart: unless-stopped
