services:
  uptime_kuma:
    container_name: uptime_kuma
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    volumes:
      - /opt/docker_volumes/uptime_kuma/data:/app/data
    ports:
      - "3001:3001"
    environment:
      - TZ=Europe/Berlin
    security_opt:
      - no-new-privileges:true
